"""
Unsupervised model: clusters logged days into behavior "types" using
KMeans, across study, health, and finance features together.

Cluster labels are generated by comparing each cluster's mean feature
values against the user's OWN overall mean/std (a z-score-like
comparison), not fixed universal thresholds — "high study" means high
*for this person*, not high against some arbitrary number. This makes
labels meaningful regardless of whether the user is, e.g., a light or
heavy studier in absolute terms.
"""

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

from config import MIN_DAYS_FOR_CLUSTERING

FEATURE_COLS = ["study_minutes", "calories", "workout_minutes", "sleep_hours", "expense_amount"]


def train_clustering_model(daily_df: pd.DataFrame, k_range=(2, 3, 4, 5)) -> dict:
    """
    Fits KMeans for each k in k_range, picks the k with the best
    silhouette score. Degrades gracefully (explicit message, no model)
    if there isn't enough data to cluster meaningfully.
    """
    available_cols = [c for c in FEATURE_COLS if c in daily_df.columns]
    df = daily_df.dropna(subset=available_cols) if not daily_df.empty else daily_df

    if df.empty or len(df) < MIN_DAYS_FOR_CLUSTERING:
        return {
            "model": None, "scaler": None, "status": "insufficient_data",
            "message": f"Only {len(df)} day(s) with complete data available. "
                       f"Need at least {MIN_DAYS_FOR_CLUSTERING} to cluster meaningfully — keep logging data.",
        }

    X = df[available_cols].values
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    best_k, best_score, best_model, best_labels = None, -1, None, None
    for k in k_range:
        if k >= len(df):
            continue
        model = KMeans(n_clusters=k, random_state=42, n_init=10)
        labels = model.fit_predict(X_scaled)
        if len(set(labels)) < 2:
            continue
        score = silhouette_score(X_scaled, labels)
        if score > best_score:
            best_k, best_score, best_model, best_labels = k, score, model, labels

    if best_model is None:
        return {"model": None, "scaler": None, "status": "no_valid_clustering",
                "message": "Could not find a valid clustering (data may be too uniform)."}

    result_df = df.copy()
    result_df["cluster"] = best_labels

    return {
        "model": best_model, "scaler": scaler, "status": "clustered",
        "k": best_k, "silhouette_score": round(best_score, 3),
        "labeled_df": result_df, "feature_cols": available_cols,
    }


def describe_clusters(cluster_bundle: dict) -> pd.DataFrame:
    """Mean feature values + day count per cluster (raw, non-interpreted)."""
    if cluster_bundle["model"] is None:
        return pd.DataFrame()

    df = cluster_bundle["labeled_df"]
    cols = cluster_bundle["feature_cols"]
    summary = df.groupby("cluster")[cols].mean().round(1)
    summary["day_count"] = df.groupby("cluster").size()
    return summary.reset_index()


def _relative_level(cluster_mean: float, overall_mean: float, overall_std: float) -> str:
    """Returns 'high' / 'low' / 'typical' relative to the user's OWN baseline."""
    if overall_std == 0 or pd.isna(overall_std):
        return "typical"
    z = (cluster_mean - overall_mean) / overall_std
    if z > 0.5:
        return "high"
    elif z < -0.5:
        return "low"
    return "typical"


def label_clusters(cluster_bundle: dict) -> list:
    """
    Generates human-readable, interpretable cluster summaries compared
    against the user's OWN historical baseline (not fixed thresholds).
    Returns a list of dicts: {cluster_id, label, day_count, characteristics}.
    """
    if cluster_bundle["model"] is None:
        return []

    df = cluster_bundle["labeled_df"]
    cols = cluster_bundle["feature_cols"]
    overall_means = df[cols].mean()
    overall_stds = df[cols].std()

    results = []
    for cluster_id, group in df.groupby("cluster"):
        cluster_means = group[cols].mean()
        levels = {
            col: _relative_level(cluster_means[col], overall_means[col], overall_stds[col])
            for col in cols
        }

        label_parts = []
        if "study_minutes" in levels and levels["study_minutes"] == "high":
            label_parts.append("High Study")
        if "workout_minutes" in levels and levels["workout_minutes"] == "high":
            label_parts.append("Active")
        if "expense_amount" in levels and levels["expense_amount"] == "high":
            label_parts.append("High Spend")
        if "sleep_hours" in levels and levels["sleep_hours"] == "low":
            label_parts.append("Low Sleep")
        if not label_parts:
            all_typical = all(v == "typical" for v in levels.values())
            label_parts.append("Balanced / Typical Day" if all_typical else "Mixed Pattern")

        label = " & ".join(label_parts[:2])

        results.append({
            "cluster_id": int(cluster_id),
            "label": label,
            "day_count": int(len(group)),
            "characteristics": {col: round(cluster_means[col], 1) for col in cols},
            "levels": levels,
        })

    results.sort(key=lambda r: r["day_count"], reverse=True)
    return results
